#!/bin/bash
recipeDirect='(select(.["@type"]=="Recipe"))'
recipeGraph='(select(has("@graph"))|.["@graph"]|map(select(.["@type"]=="Recipe"))|.[])'
recipes="(.[]|(arrays|.[]),objects|$recipeGraph,$recipeDirect)"
title='(.name+"\n"+(.name|explode|map("=")|join(""))+"\n")'
description='(.description+"\n")'
ingredientsHeader='"Ingredients\n-----------\n"'
ingredients='(.recipeIngredient|[.[]|" * "+.+"\n"]|join(""))'
instructionsHeader='"Instructions\n------------\n"'
instructionsString='strings'
howtostep='strings,(objects|select(has("@type"))|select(.["@type"]=="HowToStep"),(select(.["@type"]=="HowToSection")|.itemListElement|.[])|.text)'
instructionsArray='(arrays|([.[]|'"$howtostep"'|" * "+.+"\n"]|join("")))'
instructions="(.recipeInstructions|$instructionsString,$instructionsArray)"
br='"\n"'

curl -s "$1" | pup 'script[type="application/ld+json"] text{}'\
             | jq -rs "$recipes|$title+$br+$description+$br
                         +$ingredientsHeader+$ingredients+$br
                         +$instructionsHeader+$instructions"
